### ISSUE TITLE
Weakness?

### ISSUE THREAD

**Issue by paride** [aspiers/ANTIFOLD#1]
Hey @aspiers, I have a couple questions on this repo:

- Can't you get rid of the "Weakness" you mention in the README file simply by stowing ANTIFOLD with `--no-folding`?
- Why do you need the `.no-stow-folding` file? Stow seems to handle empty directories just fine.

Thanks for maintaining stow!

**Comment by aspiers** [comment]
[**@paride**](https://github.com/paride) commented on [July 22, 2019 9:57 AM](https://github.com/aspiers/ANTIFOLD/issues/1#issue-470974784 "2019-07-22T08:57:36Z - Replied by Github Reply Comments"):
> - Can't you get rid of the "Weakness" you mention in the README file simply by stowing ANTIFOLD with `--no-folding`?

Ummm ... good question!  Probably yes and I just didn't think of that yet!  Maybe I even wrote that text before I implemented `--no-folding`.

> - Why do you need the `.no-stow-folding` file? Stow seems to handle empty directories just fine.

Another great question.  Yes, I've just tested and it seems unnecessary.  *Maybe* it was needed in the past before I implemented `--no-folding`, or maybe I was just confusing it with git which ignores empty directories ;-)

> Thanks for maintaining stow!

You're welcome - thanks a lot for pointing out these holes in my thinking!

**Comment by aspiers** [comment]
> > - Why do you need the `.no-stow-folding` file? Stow seems to handle empty directories just fine.
> 
> Another great question.  Yes, I've just tested and it seems unnecessary.  *Maybe* it was needed in the past before I implemented `--no-folding`, or maybe I was just confusing it with git which ignores empty directories ;-)

Ohhh ... duh!  The penny dropped just after writing that :-)  The files *are* needed, because this is a git repository, so without them, the directories would not exist ...

**Comment by paride** [comment]
Right! I didn't thought of that while playing with your "antifold" strategy, even if I am keeping my dotfiles in Git. 

Thanks!
